### ISSUE TITLE
Time precision is not big enough to distinguish versions

### ISSUE THREAD

**Issue by JoaoFelipe** [gems-uff/noworkflow#119]
noWorkflow 2 uses the evaluation and member moment to distinguish the version of values. However, the collected time precision is not enough for some evaluations and it seems that there is no way to increase the precision.

We can replace this information by a sequential moment number and all version operations will keep working, but we will lose the actual moment.
Alternatively, we can create a Moment table with the following columns: trial_id, id, datetime, and use the id in this table to identify the moment in evaluations. This imposes an overhead, but keeps the time information.

Which one is the best approach?

**Comment by leomurta** [comment]
Before going into the solution, I analyzed the clock options in Python:

- [time.clock()](https://docs.python.org/3/library/time.html#time.clock): deprecated;
- [time.monotonic()](https://docs.python.org/3/library/time.html#time.monotonic): The reference point of the returned value is undefined;
- [time.perf_counter()](https://docs.python.org/3/library/time.html#time.perf_counter): The reference point of the returned value is undefined;
- [time.process_time()](https://docs.python.org/3/library/time.html#time.process_time): The reference point of the returned value is undefined;
- [time.time()](https://docs.python.org/3/library/time.html#time.time): Fits all requirements, but the precision depends on the Operating System. Python 3.7 is going to provide [time.time_ns()](https://docs.python.org/3.7/library/time.html#time.time_ns), which is similar to time.time() but with nanoseconds precision.

The time.time() function has microseconds precision in my computer. With this resolution, two consecutive calls and different indeed:

```
1524785828.291824
1524785828.291826
```

Although different, they are very near. A slightly faster computer could colide. So, I decided to look at the other "clocks" that I listed above. They are not appropriate to compute absolute time because the reference is undefined, but... what if we store the trial start time and all other times relative to this time?

My first question is: which time should I use for relative but precise time collection?

- [time.monotonic()](https://docs.python.org/3/library/time.html#time.monotonic): Seem to be a possible option. In my computer has a nanoseconds implementation;
- [time.perf_counter()](https://docs.python.org/3/library/time.html#time.perf_counter): Also seems to be a possible option. In my computer has the same implementation of time.monotonic();
- [time.process_time()](https://docs.python.org/3/library/time.html#time.process_time): Not an option because counts only system and user CPU time of the current process, missing, for example, sleep time;

Although time.monotonic() and time.perf_counter() have the same implementation, the documentation of time.perf_counter() states that "a clock with the highest available resolution to measure a short duration". It is not clear to me what they mean "short duration", but I liked the part "highest available resolution", so I used this clock for my tests. The tests are basically this:

```python
count = 0
for i in range(100000):
    if time.time() - time.time() == 0:
        count += 1
print('Colision with time.time()',count,'in 100000')
```

The result is 89% of collision when using time.time(). Then I did the following:

```python
count = 0
for i in range(100000):
    if time.perf_counter() - time.perf_counter() == 0:
        count += 1
print('Colision with time.perf_counter()',count,'in 100000')
```

The result was zero collision when using time.perf_counter(). This seems to be good news. So, I implemented the following prototype of my idea of using both clocks: a wall clock (time.time()) for linking the trial with the world and a precision clock, for internal measurements of time:

```python
import time

def print_time(i):
    relative_time = time.perf_counter()
    delta_time = relative_time - reference_time
    print('Time measured at moment', i)
    print('    Relative time:',relative_time)
    print('    Delta since the beginning: %.9f' % delta_time)
    print('    Current wall time: %.9f' % (wall_time + delta_time))

wall_time = time.time()
reference_time = time.perf_counter()

print('Wall time at the beginning of the trial:', wall_time)
print('Reference internal time:', reference_time)

for i in range(10):
    print_time(i)
```

The output of this program shows both the delta since the beginning of the trial and the wall time at any moment using the first wall time and the delta. Can we use such strategy, recording just once the wall time and recording the delta since the moment we started the trial in each collection moment? Does it imply high overhead? Instead of delta, we could also store both wall time and perf time in the trial and store the perf time in each collection moment, requiring the user to do the math. Another option is to store the delta as a int in nanoseconds. Not sure if it helps or not.
