### ISSUE TITLE
Pack the content DB

### ISSUE THREAD

**Issue by leomurta** [gems-uff/noworkflow#99]
We are currently using a basic mechanism for storing content of files, as described here (http://schacon.github.io/gitbook/7_how_git_stores_objects.html). This is nice because we do not duplicate content in the database, but after any small change in the file the entire new content is stored. An alternative is to adopt some strategy to pack the content, like this (http://schacon.github.io/gitbook/7_the_packfile.html).

**Comment by leomurta** [comment]
We can think about using git as a lib instead implementing it. This way, we would not need to go into the details of such implementation and would receive improvements from time to time when they release new versions of the lib. 

Take a look on this: https://libgit2.github.com/. A C lib is even better, as it is probably faster. It has a Python binding (http://www.pygit2.org/), but it requires libgit2 to be installed. Can we add a C lib as dependency in pip and automatically install it? The key point here is being transparent to the user (we should not require Git in his computer or any additional installation procedure). 

I also found this: https://github.com/gitpython-developers/gitdb. It is pure Python API to the Git database. This is good for transparency, but may be bad for performance (which is critical here). We need to check.

**Comment by JoaoFelipe** [comment]
It is possible to add a C lib in the project and submit it to PyPI. However, the deploy to PyPI will become a bit more complicated, as it will either require users to have C compilers or require us to cross-compile for multiple python and system versions. Linux users will necessarily need C compilers.

I actually want to use Cython (optionally) to optimize some parts of the collection. So maybe, we can use this library and Cython if the user has whats is necessary for C extensions, and fallback to gitdb (and pure python collection), otherwise

**Comment by leomurta** [comment]
What about doing some benchmark of gitdb and C libgit2 (and even directly call to git) just to give us a notion of how fast are these options. I would say that we could stick with just gitdb if it is not much slower than the other options.

**Comment by JoaoFelipe** [comment]
It has been implemented by Vynicius
